// 1. Creación de un Objeto Básico:
// Crea un objeto llamado libro con propiedades como título, autor y añoDePublicacion. Imprime cada propiedad en la consola.

const libro= {
    titulo: 'Cien Años de Soledad',
    autor: 'Gabriel Garcia Marquez',
    añoDePublicacion: 1967
}

console.log(libro)
console.log('Titulo: ' + libro.titulo)
console.log('Autor: ' + libro.autor)
console.log('Año de publicacion: ' + libro.añoDePublicacion)
